package tablas_Clases;

// default package
// Generated 09-jun-2015 15:28:21 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Regions generated by hbm2java
 */
@SuppressWarnings("serial")
public class Regions implements java.io.Serializable {

	private BigDecimal regionId;
	private String regionName;
	@SuppressWarnings("rawtypes")
	private Set countrieses = new HashSet(0);

	public Regions() {
	}

	public Regions(BigDecimal regionId) {
		this.regionId = regionId;
	}

	public Regions(BigDecimal regionId, String regionName, @SuppressWarnings("rawtypes") Set countrieses) {
		this.regionId = regionId;
		this.regionName = regionName;
		this.countrieses = countrieses;
	}

	public BigDecimal getRegionId() {
		return this.regionId;
	}

	public void setRegionId(BigDecimal regionId) {
		this.regionId = regionId;
	}

	public String getRegionName() {
		return this.regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@SuppressWarnings("rawtypes")
	public Set getCountrieses() {
		return this.countrieses;
	}

	public void setCountrieses(@SuppressWarnings("rawtypes") Set countrieses) {
		this.countrieses = countrieses;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return regionName;
	}

}
